feat: add ability to attach access tags to resources
terraform-ibm-modules/terraform-ibm-key-protect pull request #304
Opened 2023-04-04 21:44 UTC by MatthewLemmond

### Description
provide the ability to add access tags to resources created by the module 

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [x] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Add ability to attach access tags to resources created by the module, consumers who want to use the access tags will need additional permissions for Tagging service at the Administrator level

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-04-05 21:31 UTC, MatthewLemmond commented
Skipping upgrade test, tested upgrade path manually and saw no destroys when not providing access tags, after providing access tags only the resource tag was add to the terraform state and nothing was destroyed. Here is the plan after applying the main branch:
```
Terraform will perform the following actions:

  # module.key_protect_module.ibm_resource_tag.key_protect_tag[0] will be created
  + resource "ibm_resource_tag" "key_protect_tag" {
      + acccount_id = (known after apply)
      + id          = (known after apply)
      + resource_id = "crn:v1:bluemix:public:kms:eu-gb:a/abac0df06b644a9cabc6e44f55b3880e:7e3b1271-02e6-41b3-8571-77e1e716ae0f::"
      + tag_type    = "access"
      + tags        = [
          + "geretain-dev:permanent-test-tag-1",
          + "geretain-dev:permanent-test-tag-2",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.key_protect_module.ibm_resource_tag.key_protect_tag[0]: Creating...
module.key_protect_module.ibm_resource_tag.key_protect_tag[0]: Creation complete after 1s [id=crn:v1:bluemix:public:kms:eu-gb:a/abac0df06b644a9cabc6e44f55b3880e:7e3b1271-02e6-41b3-8571-77e1e716ae0f::]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Note: upgrade test is failing due to passing the access_tags variable into the test which causes the main branch apply to fail due to the variable not being present in previous versions of the module.

2023-04-28 17:13 UTC, toddgiguere submitted a review, later dismissed

2023-05-11 08:36 UTC, ocofaigh requested changes
one comment

2023-05-15 19:05 UTC, ocofaigh approved these changes

2023-05-15 19:05 UTC, merged

2023-05-15 19:15 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: