Onboard module into ibm registry
terraform-ibm-modules/terraform-ibm-key-protect pull request #471
Opened 2023-11-17 12:20 UTC by rajatagarwal-ibm

### Description

Onboarding to IBM Registry

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-17 12:23 UTC, rajatagarwal-ibm commented
/run pipeline

2023-11-17 12:40 UTC, rajatagarwal-ibm commented
Adding "cra-config" in a separate PR first.

2023-11-17 12:43 UTC, ocofaigh requested changes
some small comments

2023-11-17 12:43 UTC, ocofaigh commented on ibm_catalog.json
> +        "key protect",
can keywords have spaces? maybe they can?

2023-11-17 12:43 UTC, ocofaigh commented on ibm_catalog.json
> +        "authorization",
Perhaps encryption instead of authorization?

2023-11-17 12:43 UTC, ocofaigh commented on ibm_catalog.json
> +        }
Perhaps also add "Attach resource tags"

2023-11-17 12:50 UTC, rajatagarwal-ibm commented on ibm_catalog.json
> +        "key protect",
I assume they can as many services have multi-word names

2023-11-17 13:29 UTC, rajatagarwal-ibm commented
/run pipeline

2023-11-17 13:38 UTC, rajatagarwal-ibm commented
/run pipeline

2023-11-17 14:05 UTC, SirSpidey submitted a review, later dismissed
Committed some description updates. 

We still need the placeholder diagram, caption, and description, right?

2023-11-17 14:12 UTC, rajatagarwal-ibm commented
/run pipeline

2023-11-17 14:14 UTC, rajatagarwal-ibm commented
@SirSpidey placeholder diagram for the example is mentioned in the ibm_catalog.json file along with some description. Are you looking for something else here?

2023-11-17 14:54 UTC, SirSpidey commented
> @SirSpidey placeholder diagram for the example is mentioned in the ibm_catalog.json file along with some description. Are you looking for something else here?

Nope. Just missed it and forgot that the digram is not hosted in the repo.

2023-11-20 17:18 UTC, ocofaigh requested changes
see comment

2023-11-20 17:18 UTC, ocofaigh commented on ibm_catalog.json
> +      "long_description": "Use this module to provision and configure an IBM Key Protect instance.\nYou can configure the following aspects of your instance:\n- [Key Protect instance](https://cloud.i
- source needs to be updated to `https://cm.globalcatalog.cloud.ibm.com/api/v1-beta/offering/source?archive=tgz&kind=terraform&name=terraform-ibm-key-protect&version=X.X.X`
- Move this comment so it shows above the source: `# Replace "X.X.X" with a release version to lock into a specific release`
- Missing a `\n` at the end. The ``` should be on the last line:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/assets/29608224/ed9e15ab-362e-4216-acfe-032050b458e6)

2023-11-22 09:51 UTC, rajatagarwal-ibm commented
/run pipeline

2023-11-22 10:00 UTC, ocofaigh approved these changes

2023-11-22 10:00 UTC, merged

2023-11-22 10:02 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.4.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/releases/tag/v2.4.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: